### ISSUE TITLE
Deprecation spam

### ISSUE THREAD

**Issue by FluffyDiscord** [DamienHarper/auditor#149]
| Q                           | A
| ----------------------------| -----------------------
| `auditor-bundle` version    | 5.2.1
| `auditor` version    | 2.4.2
| PHP version                 |v8.1.13
| Database                    | PostgreSQL 
| Doctrine ORM | 2.13.1
| Doctrine DBAL | 3.4.0
| Symfony | 6.1.2

#### Summary

Auditor/bundle uses some deprecated classes. Its spamming deprecations on any DB operation and
1. eats memory because in dev env in symbony logs stay in memory and make you believe you have false memory leak
2. makes the deprecation log full of errors I can not fix

#### Current behavior

deprecation.INFO: User Deprecated: Since damienharper/auditor 2.2: SQLLogger is deprecated. Use DHMiddleware instead {"exception":"[object] (ErrorException(code: 0): User Deprecated: Since damienharper/auditor 2.2: SQLLogger is deprecated. Use DHMiddleware instead at /var/www/app/vendor/damienharper/auditor/src/Provider/Doctrine/Auditing/Event/DoctrineSubscriber.php:51)

#### How to reproduce

Any DB operation - insert/update etc

#### Expected behavior

Either add option to disable deprecation logging (eg. have it enabled only when testing this library) or remove it entirely.

**Comment by craigh** [comment]
@DamienHarper I'd like to correct this in my code as well but don't understand the deprecation message.

> User Deprecated: Since damienharper/auditor 2.2: SQLLogger is deprecated. Use DHMiddleware instead

Is there some documentation on how to "use DHMiddleware" and why it is needed?

I found this: https://github.com/DamienHarper/auditor-bundle/pull/331 but don't understand what @dmitryuk means by "But now the error not caused by auditor package and must be resolved outside the package."

Help is appreciated.

**Comment by dmitryuk** [comment]
@FluffyDiscord, What version of `damienharper/auditor-bundle` do you have in `composer.lock`? 

If you have `DoctrineProviderConfigurationCompilerPass` easiest way to understand the problem is to manually debug the `process` method. Looks like `$configuration->addMethodCall('setMiddlewares', [[$DHMiddlewareDef]]);` never executes

**Comment by dmitryuk** [comment]
@craigh `SqlLogger` is deprecated since Doctrine have created a new [Middleware](https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/architecture.html#middlewares) way to do the same.

About my comment - anyway if I don't use `SqlLogger` Symfony defines service named `DbalLogger implements SqlLogger` and we see a deprecation error:
```
User Deprecated: The "Symfony\Bridge\Doctrine\Logger\DbalLogger" class implements "Doctrine\DBAL\Logging\SQLLogger" that is deprecated Use {@see \Doctrine\DBAL\Logging\Middleware} or implement {@see \Doctrine\DBAL\Driver\Middleware} instead.
```

https://github.com/DamienHarper/auditor-bundle/pull/331#issuecomment-1313059537

**Comment by craigh** [comment]
@dmitryuk thanks for your reply, but I am still completely baffled. 😕 I have a very standard installation of auditor-bundle v5.2.1

dh_auditor.yaml
```yaml
dh_auditor:
    providers:
        doctrine:
            viewer: true
            ignored_columns:
                - 'createdAt'
                - 'updatedAt'
            entities:
                App\Entity\User:
                    roles:
                        view:
                            - 'ROLE_SUPER_ADMIN'
```
but in `test` environment, I do this:

```yaml
dh_auditor:
    enabled: false
```

**Comment by dmitryuk** [comment]
What version of `doctrine/dbal` do you have in `composer.lock`?

**Comment by craigh** [comment]
```json
            "name": "doctrine/dbal",
            "version": "3.5.2",
```

**Comment by dmitryuk** [comment]
I checked and found that issue already fixed in
https://github.com/DamienHarper/auditor-bundle/commit/e5843741d834d14b8dca4bd06cc645055921826b#diff-5864ffa23fdebf7326e8f8e2363c59b16447da425ce48776db1bc833fd832d02R24

`DoctrineProviderConfigurationCompilerPass` was loaded after `Doctrine\MiddlewaresPass` so it didn't work properly
@DamienHarper, please make a new tag of auditor-bundle to apply changes.

**Comment by dmitryuk** [comment]
@DamienHarper, ping

**Comment by dmitryuk** [comment]
@FluffyDiscord Please install latest version of `damienharper/auditor-bundle:^5.2.2" - issue must be fixed

**Comment by dmitryuk** [comment]
Done in `5.2.3`, @DamienHarper close issue

**Comment by Marmelatze** [comment]
The problem still exists when using sentry and dh auditor together, as sentry adds itself to the end of the doctrine middlewares: https://github.com/getsentry/sentry-symfony/blob/master/src/DependencyInjection/Compiler/DbalTracingPass.php#L71

This fails the drive instance check, as the last :

```php
$driver = $entityManager->getConnection()->getDriver();
        if ($driver instanceof DHDriver) {
```

I don't see a way to check if DHDriver is wrapped somewhere in the middleware chain... So my hacky workaround is to put the DHMiddleware to the end again:

```php
<?php
namespace App\DependencyInjection\CompilerPass;

use Symfony\Component\DependencyInjection\ChildDefinition;
use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;

class DoctrineMiddlewarePass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container)
    {
        $definition = $container->getDefinition('doctrine.dbal.default_connection.configuration');
        foreach ($definition->getMethodCalls() as $methodCall) {
            if ('setMiddlewares' !== $methodCall[0]) {
                continue;
            }
            // get DH middleware and put it to the end
            $dhMiddleware = null;
            $calls = $methodCall[1];
            foreach ($calls[0] as $key => $call) {
                if ($call instanceof ChildDefinition
                    && 'doctrine.dbal.default_connection.dh_middleware' === $call->getParent()) {
                    $dhMiddleware = $key;
                    break;
                }
            }
            if (null === $dhMiddleware) {
                throw new \InvalidArgumentException('dh middleware not found in setMiddlewares call');
            }
            $dhCall = $calls[0][$dhMiddleware];
            unset($calls[0][$dhMiddleware]);
            $calls[0][] = $dhCall;

            $definition->removeMethodCall('setMiddlewares');
            $definition->addMethodCall('setMiddlewares', $calls);
        }
    }
}
```

And add the compiler pass to the Kernel:
```php
        $container->addCompilerPass(new DoctrineMiddlewarePass(), PassConfig::TYPE_BEFORE_OPTIMIZATION, -100);
```
